CREATE TABLE IF NOT EXISTS exam_categories (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    slug VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    status ENUM('active', 'inactive') DEFAULT 'active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS idioms (
    id INT AUTO_INCREMENT PRIMARY KEY,
    idiom VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL UNIQUE,
    english_meaning TEXT,
    hindi_meaning TEXT,
    explanation TEXT,
    example_sentence TEXT,
    memory_trick TEXT,
    synonyms TEXT,
    antonyms TEXT,
    category_id INT NULL,
    difficulty ENUM('Easy', 'Moderate', 'Hard', 'Very Important') DEFAULT 'Moderate',
    exam_type VARCHAR(255) NULL,
    related_content TEXT NULL,
    meta_title VARCHAR(255) NULL,
    meta_description TEXT NULL,
    meta_keywords TEXT NULL,
    canonical_url VARCHAR(255) NULL,
    featured TINYINT(1) DEFAULT 0,
    status ENUM('Draft', 'Published') DEFAULT 'Draft',
    views INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX (slug),
    INDEX (status),
    INDEX (category_id),
    INDEX (featured),
    FOREIGN KEY (category_id) REFERENCES exam_categories(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS phrasal_verbs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    phrasal_verb VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL UNIQUE,
    english_meaning TEXT,
    hindi_meaning TEXT,
    explanation TEXT,
    example_sentence TEXT,
    memory_trick TEXT,
    synonyms TEXT,
    antonyms TEXT,
    category_id INT NULL,
    difficulty ENUM('Easy', 'Moderate', 'Hard', 'Very Important') DEFAULT 'Moderate',
    exam_type VARCHAR(255) NULL,
    related_content TEXT NULL,
    meta_title VARCHAR(255) NULL,
    meta_description TEXT NULL,
    meta_keywords TEXT NULL,
    canonical_url VARCHAR(255) NULL,
    featured TINYINT(1) DEFAULT 0,
    status ENUM('Draft', 'Published') DEFAULT 'Draft',
    views INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX (slug),
    INDEX (status),
    INDEX (category_id),
    INDEX (featured),
    FOREIGN KEY (category_id) REFERENCES exam_categories(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS practice_questions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    content_type ENUM('idiom', 'phrasal_verb', 'vocabulary', 'general') DEFAULT 'general',
    content_id INT NULL,
    question TEXT NOT NULL,
    option_a VARCHAR(255) NOT NULL,
    option_b VARCHAR(255) NOT NULL,
    option_c VARCHAR(255) NOT NULL,
    option_d VARCHAR(255) NOT NULL,
    correct_answer ENUM('A', 'B', 'C', 'D') NOT NULL,
    explanation TEXT,
    hindi_explanation TEXT,
    difficulty ENUM('Easy', 'Moderate', 'Hard', 'Very Important') DEFAULT 'Moderate',
    exam_type VARCHAR(255) NULL,
    status ENUM('Draft', 'Published') DEFAULT 'Published',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
